# Generated by Django 4.0.2 on 2022-06-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('imageURL', models.CharField(blank=True, max_length=5000, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
