# Generated by Django 4.0.2 on 2022-07-01 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
